### ISSUE TITLE
action auto-builds have expired

### ISSUE THREAD

**Issue by DaoWen** [SonixQMK/sonix-flasher#16]
I was following @CalcProgrammer1's awesome youtube guide on flashing the GMMK with QMK (https://youtu.be/aUiKHdI5Vk8?t=924), and it says to grab the latest sonix-flasher build from the actions artifacts in this project. However, all of the recent builds have expired, and the artifacts are gone.

Short-term, could you please trigger another build? I ran into two other people in the gmmk channel in this project's discord today that were trying to follow the same video and similarly couldn't find a working download.

Longer-term, maybe you can [add a schedule to the workflow](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events) to run once a week.

**Comment by jindaxia** [comment]
@CalcProgrammer1   push a tag with vX.x , then the artifacts will add to the release page

**Comment by jindaxia** [comment]
@DaoWen  release  v0.2.2

**Comment by DaoWen** [comment]
谢了虾哥!
