### ISSUE TITLE
Run without GUI

### ISSUE THREAD

**Issue by NilsIrl** [SonixQMK/sonix-flasher#24]
The dependency on qt makes this a pain to run.

Is there a way to run a command from the CLI to flash?

**Comment by NilsIrl** [comment]
I wrote a simple script that just flashes a firmware and only depends on `hidapi` (the dependency I was having trouble with is pyqt)).

I would be happy to contribute it back.

**Comment by tfuxu** [comment]
I suppose you can use https://github.com/SonixQMK/SonixFlasherC if you just want a CLI.

**Comment by jindaxia** [comment]
use https://github.com/SonixQMK/SonixFlasherC
