### ISSUE TITLE
Should 0x200 be the default?

### ISSUE THREAD

**Issue by Krutonium** [SonixQMK/sonix-flasher#4]
While I was making the Window taller, I noticed it would be easy to change that default, so I am curious if there is any desire for 0x00 to be the default, or perhaps for it to change based on what bootloader pid/vid is detected?

**Comment by CalcProgrammer1** [comment]
Related to your PR, could you make it so that if the keyboard is a 26x, then it checks 0x200 by default, but if it is a 24x, it selects 0x00 by default?  The 0x200 is necessary if you have jumploader installed, which should be all 26x keyboards because of the brick risk.

**Comment by Krutonium** [comment]
I can see about making that happen, sure!
