### ISSUE TITLE
Error when flashing a second time

### ISSUE THREAD

**Issue by CalcProgrammer1** [SonixQMK/sonix-flasher#8]
If you try to flash a second time, it throws an error.

Procedure:

1. Open sonix flasher with ./run.sh
2. Keyboard already in bootloader, so just click flash QMK and pick .bin
3. Flashes successfully
4. Put keyboard in bootloader with key combination
5. Refresh, select SN32F248B (bootloader)
6. Try to flash QMK again
7. Error:

![image](https://user-images.githubusercontent.com/1051772/128609827-cc37ceec-a54a-4466-a894-c43328de7947.png)

**Comment by Krutonium** [comment]
I've verified this but I can't figure out what exactly is the issue.
